name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  path_provider:

  alfred:

  # db stuff
  drift: ^2.25.1
  sqlite3: ^2.7.3
  uuid:

  dotenv:

  # encryption
  crypto:
  aescryptojs:

  # tokens
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

  # db stuff
  drift_dev: ^2.25.2
  build_runner: ^2.4.15
